apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: homebridge
  namespace: homebridge
spec:
  rules:
  - host: homebridge.wolfe.int
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: homebridge
            port:
              number: 8080
      - backend:
          serviceName: homebridge
          servicePort: 8080
