metadata:
  chartname: stable/nginx-ingress
  release:
    name: nginx-ingress
    namespace: kube-system
controller:
  image:
    registry: us.gcr.io
    repository: k8s-artifacts-prod/nginx-ingress-controller-arm
    tag: 0.9.0-beta.15
    pullPolicy: IfNotPresent
    runAsUser: 33
defaultBackend:
  enabled: true
  name: default-backend
  image:
    repository: k8s.gcr.io/defaultbackend-arm
    tag: "1.5"
    pullPolicy: IfNotPresent
    runAsUser: 65534
