metadata:
  chartname: hashicorp/consul
  release:
    name: consul
    namespace: consul

global:
  enabled: true
  name: consul
  datacenter: vault
  image: "consul:1.9.5"
  imageK8S: hashicorp/consul-k8s:0.25.0
  gossip_encryption:
    secret_name: consul-gossip-encryption-key
    secret_key: key

server:
  storage: 1Gi

ui:
  ingress:
    enabled: true
    hosts:
      - host: consul.wolfe.int
        paths:
          - /

client:
  enabled: false

dns:
  enabled: false
