apiVersion: v1
kind: Service
metadata:
  labels:
    app: mozillaiot-gateway
  name: mozillaiot-gateway
  namespace: mozillaiot
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: mozillaiot-gateway
  type: ClusterIP
