apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: mozillaiot-gateway
  namespace: mozillaiot
spec:
  rules:
  - host: iot.wolfe.int
    http:
      paths:
      - backend:
          serviceName: mozillaiot-gateway
          servicePort: 80
