metadata:
  chartname: hashicorp/vault
  release:
    name: vault
    namespace: vault

global:
  enabled: true

injector:
  enabled: false

server:
  enabled: true
  image:
    repository: "vault"
    tag: "1.7.0"
    pullPolicy: Always

  dataStorage:
    size: 1Gi

  ingress:
    enabled: true
    hosts:
      - host: vault.wolfe.int
        paths: []

  authDelegator:
    enabled: false

  ha:
    enabled: true
    replicas: 3

    apiAddr: null

    config: |
      ui = true
      max_lease_ttl = "12h"
      default_lease_ttl = "12h"

      listener "tcp" {
        tls_disable = 1
        address = "[::]:8200"
        cluster_address = "[::]:8201"
      }
      storage "consul" {
        path = "vault"
        address = "consul-server.consul:8500"
      }

      service_registration "kubernetes" {}
