---
# Source: netgear-exporter/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: netgear-exporter
  namespace: netgear-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: netgear-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/name: netgear-exporter
    spec:
      containers:
        - name: netgear-exporter
          image: stephenwolfe/netgear_exporter:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: NETGEAR_EXPORTER_WEB_LISTEN_ADDRESS
              value: ":9192"
            - name: NETGEAR_EXPORTER_INSECURE
              value: "true"
            - name: NETGEAR_EXPORTER_CLIENT_DEBUG
              value: "false"
            - name: NETGEAR_EXPORTER_TIMEOUT
              value: "10"
            - name: NETGEAR_EXPORTER_URL
              value: "http://www.routerlogin.com"
            - name: NETGEAR_EXPORTER_USERNAME
              value: admin
            - name: NETGEAR_EXPORTER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: netgear-exporter
                  key: NETGEAR_EXPORTER_PASSWORD
          ports:
            - name: http
              containerPort: 9192
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
