apiVersion: v1
kind: Service
metadata:
  name: netgear-exporter
  namespace: netgear-exporter
  labels:
    app.kubernetes.io/name: netgear-exporter
spec:
  ports:
  - name: http
    port: 9192
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/name: netgear-exporter
  type: ClusterIP
