apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: netgear-exporter-sm
  namespace: netgear-exporter
  labels:
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: netgear-exporter
  endpoints:
  - port: http
